// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6554.GearRunner;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import org.usfirst.frc6554.GearRunner.commands.ArcadeDrive;
import org.usfirst.frc6554.GearRunner.commands.AutonomousCommand;
import org.usfirst.frc6554.GearRunner.recordable.DriveTrainState;
import org.usfirst.frc6554.GearRunner.recordable.Recorder;
import org.usfirst.frc6554.GearRunner.subsystems.Climber;
import org.usfirst.frc6554.GearRunner.subsystems.Drivebase;
import org.usfirst.frc6554.GearRunner.subsystems.LEDs;
import org.usfirst.frc6554.GearRunner.subsystems.pusher;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.Sendable;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

	Command autonomousCommand;
	SendableChooser<String> chooser;

	public static OI oi;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static pusher pusher;
	public static Drivebase drivebase;
	public static Climber climber;
	public static LEDs lEDs;
	public static Timer timer = new Timer();
//	public static Recorder<DriveTrainState> recorder;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	/**
	 * This function is run when the robot is first started up and should be
	 * used for any initialization code.
	 */
	ADXRS450_Gyro gyro;
	public final double kp = 0.3;
	public boolean extended = false;
	
	String auto;

	public void robotInit() {
		RobotMap.init();
		// CameraServer server = CameraServer.getInstance();
		// server.startAutomaticCapture(0);
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		pusher = new pusher();
		drivebase = new Drivebase();
		climber = new Climber();
		lEDs = new LEDs();
		//recorder = new Recorder<>(drivebase);
		SmartDashboard.putData("Pdp", new PowerDistributionPanel());
		
		chooser = new SendableChooser<>();
		chooser.addDefault("center gear", "CENTER_AUTO");
		chooser.addObject("recorded auto", "RECORDER_AUTO");
		SmartDashboard.putData("Auto chooser", chooser);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		// ADXRS450_Gyro

		gyro = new ADXRS450_Gyro();
		gyro.reset();
		gyro.calibrate();
		CameraServer.getInstance().startAutomaticCapture();

		// OI must be constructed after subsystems. If the OI creates Commands
		// (which it very likely will), subsystems are not guaranteed to be
		// constructed yet. Thus, their requires() statements may grab null
		// pointers. Bad news. Don't move it.

		// CameraServer server = CameraServer.getInstance();
		// server.setSize(0);
		// server.startAutomaticCapture(0);
		// server.startAutomaticCapture();

		oi = new OI();

		// instantiate the command used for the autonomous period
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

		autonomousCommand = new AutonomousCommand();

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	}

	/**
	 * This function is called when the disabled button is hit. You can use it
	 * to reset subsystems before shutting down.
	 */
	public void disabledInit() {
	//	recorder.cancel();
	}

	public void disabledPeriodic() {
		Scheduler.getInstance().run();
	}

	public void autonomousInit() {
		// schedule the autonomous command (example)
	/*	auto = chooser.getSelected();
		if (auto.equals("RECORDER_AUTO")) {
			try {
				recorder = (Recorder<DriveTrainState>) Recorder.recall(new FileInputStream("/home/lvuser/record.record"));
			} catch (ClassNotFoundException e) {
				e.printStackTrace();
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}
			recorder.setModePlayback();
			recorder.start();
		}else if (auto.equals("CENTER_AUTO")) {*/
			timer.reset();
			timer.start();
		
		

		if (autonomousCommand != null)
			autonomousCommand.start();

	}

	/**
	 * This function is called periodically during autonomous
	 */
	public void autonomousPeriodic() {
		
		//if (auto.equals("CENTER_AUTO")) {
			double currenttime = timer.get();
			double angle = gyro.getAngle();
		// double lencoder = leftencoder.getValue();
		// double rencoder = rightencoder.getValue();


		

		if (currenttime > 0.5 && currenttime < 3.2) {
			//was at 4.7
			drivebase.arcadeDrive(-.7, (   - angle) * kp);
			Timer.delay(0.01); }
		
		if (currenttime > 3.4 && currenttime < 3.54) {
			//was at 4.7
			drivebase.arcadeDrive(1, (   - angle) * kp);
			Timer.delay(0.01); }

      
	/*	if (currenttime > 4 && currenttime < 4.2) {
			extended = true;
			pusher.extend();
		}
		
		if (currenttime > 4.2 && currenttime < 4.25) {
			extended = true;
			pusher.retract();
		}
		
		if (currenttime > 4.25 && currenttime < 4.4) {
			extended = true;
			pusher.extend();
		}
		
		if (currenttime > 4.4 && currenttime < 4.45) {
			extended = true;
			pusher.retract();
		}
		
		
		if (currenttime > 4.5 && currenttime < 5.5) {
			
			drivebase.arcadeDrive(.7, -angle * kp);

			Timer.delay(0.01);
		}
		*/
//comment out if doing straight baseline
		       
		//
 
	//	}
		Scheduler.getInstance().run();
      }

	public void teleopInit() {
		// This makes sure that the autonomous stops running when
		// teleop starts running. If you want the autonomous to
		// continue until interrupted by another command, remove
		// this line or comment it out.
		if (autonomousCommand != null)
			autonomousCommand.cancel();
		//recorder.setModeRecord();
		//recorder.start();
		new ArcadeDrive().start();
	}

	/**
	 * This function is called periodically during operator control
	 */
	public void teleopPeriodic() {
		System.out.println(gyro.getAngle()); 
		Scheduler.getInstance().run();
	}

	/**
	 * This function is called periodically during test mode
	 */
	public void testPeriodic() {
		LiveWindow.run();
	}
}
